# Generated by Django 4.2.21 on 2026-04-16 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность, сек.'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20, verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='course',
            name='assessment_policy',
            field=models.TextField(blank=True, verbose_name='Политика оценивания'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('autumn', 'Осенний семестр'), ('spring', 'Весенний семестр')], default='autumn', max_length=10, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Код дисциплины'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Активное обучение'), ('completed', 'Курс завершен'), ('archived', 'Архивная запись')], default='active', max_length=20, verbose_name='Статус записи'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Базовый'), ('intermediate', 'Повышенный'), ('advanced', 'Высокий')], default='basic', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, verbose_name='Показывать правильные ответы студенту'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст объявления')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное объявление')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='testing.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('-is_important', '-published_at'),
            },
        ),
    ]
