# Generated by Django 4.2.21 on 2026-04-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0002_attempt_duration_seconds_course_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(verbose_name='РљРѕРјРјРµРЅС‚Р°СЂРёР№ РїСЂРµРїРѕРґР°РІР°С‚РµР»СЏ')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Р”Р°С‚Р° РїСЂРѕРІРµСЂРєРё')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='testing.attempt', verbose_name='РџРѕРїС‹С‚РєР°')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_reviews', to=settings.AUTH_USER_MODEL, verbose_name='РџСЂРµРїРѕРґР°РІР°С‚РµР»СЊ')),
            ],
            options={
                'verbose_name': 'РљРѕРјРјРµРЅС‚Р°СЂРёР№ РїРѕ РїРѕРїС‹С‚РєРµ',
                'verbose_name_plural': 'РљРѕРјРјРµРЅС‚Р°СЂРёРё РїРѕ РїРѕРїС‹С‚РєР°Рј',
                'ordering': ('-reviewed_at',),
            },
        ),
    ]
