# Generated by Django 4.2.21 on 2026-04-20 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0003_attemptreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответы')),
                ('last_question_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Последний измененный вопрос')),
                ('autosave_count', models.PositiveIntegerField(default=0, verbose_name='Число автосохранений')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Сохранено')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='testing.attempt', verbose_name='Черновик попытки')),
            ],
            options={
                'verbose_name': 'Черновик попытки',
                'verbose_name_plural': 'Черновики попыток',
                'ordering': ('-saved_at',),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('announcement', 'Объявление'), ('quiz', 'Тест'), ('attempt', 'Попытка'), ('review', 'Проверка')], max_length=20, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Текст')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.attempt', verbose_name='Попытка')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.course', verbose_name='Курс')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.quiz', verbose_name='Тест')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('is_read', '-created_at'),
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='testing_use_recipie_5ab7eb_idx')],
            },
        ),
    ]
