# Generated by Django 4.2.21 on 2026-04-20 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0003_attemptreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers_payload', models.JSONField(blank=True, default=dict, verbose_name='РћС‚РІРµС‚С‹')),
                ('last_question_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='РџРѕСЃР»РµРґРЅРёР№ РёР·РјРµРЅРµРЅРЅС‹Р№ РІРѕРїСЂРѕСЃ')),
                ('autosave_count', models.PositiveIntegerField(default=0, verbose_name='Р§РёСЃР»Рѕ Р°РІС‚РѕСЃРѕС…СЂР°РЅРµРЅРёР№')),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='РЎРѕС…СЂР°РЅРµРЅРѕ')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='testing.attempt', verbose_name='Р§РµСЂРЅРѕРІРёРє РїРѕРїС‹С‚РєРё')),
            ],
            options={
                'verbose_name': 'Р§РµСЂРЅРѕРІРёРє РїРѕРїС‹С‚РєРё',
                'verbose_name_plural': 'Р§РµСЂРЅРѕРІРёРєРё РїРѕРїС‹С‚РѕРє',
                'ordering': ('-saved_at',),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('announcement', 'РћР±СЉСЏРІР»РµРЅРёРµ'), ('quiz', 'РўРµСЃС‚'), ('attempt', 'РџРѕРїС‹С‚РєР°'), ('review', 'РџСЂРѕРІРµСЂРєР°')], max_length=20, verbose_name='РљР°С‚РµРіРѕСЂРёСЏ')),
                ('title', models.CharField(max_length=200, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє')),
                ('message', models.TextField(blank=True, verbose_name='РўРµРєСЃС‚')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='РЎСЃС‹Р»РєР°')),
                ('is_read', models.BooleanField(default=False, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ РІ')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.attempt', verbose_name='РџРѕРїС‹С‚РєР°')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.course', verbose_name='РљСѓСЂСЃ')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='testing.quiz', verbose_name='РўРµСЃС‚')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СѓС‡Р°С‚РµР»СЊ')),
            ],
            options={
                'verbose_name': 'РЈРІРµРґРѕРјР»РµРЅРёРµ',
                'verbose_name_plural': 'РЈРІРµРґРѕРјР»РµРЅРёСЏ',
                'ordering': ('is_read', '-created_at'),
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='testing_use_recipie_5ab7eb_idx')],
            },
        ),
    ]
