# Generated by Django 4.2.21 on 2026-04-21 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0004_attemptdraft_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_limit_minutes_snapshot',
            field=models.PositiveIntegerField(default=0, verbose_name='Лимит времени для попытки, мин.'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('announcement', 'Объявление'), ('quiz', 'Тест'), ('attempt', 'Попытка'), ('review', 'Проверка'), ('appeal', 'Апелляция')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='QuizAccessOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Дополнительное время, мин.')),
                ('extra_attempts', models.PositiveIntegerField(default=0, verbose_name='Дополнительные попытки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_overrides', to='testing.quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_access_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Индивидуальные условия',
                'verbose_name_plural': 'Индивидуальные условия',
                'ordering': ('student__last_name', 'student__first_name', 'student__username'),
            },
        ),
        migrations.CreateModel(
            name='AttemptAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус апелляции')),
                ('message', models.TextField(verbose_name='Текст апелляции')),
                ('teacher_response', models.TextField(blank=True, verbose_name='Ответ преподавателя')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено в')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='testing.attempt', verbose_name='Попытка')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_attempt_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Апелляция по попытке',
                'verbose_name_plural': 'Апелляции по попыткам',
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='quizaccessoverride',
            constraint=models.UniqueConstraint(fields=('quiz', 'student'), name='unique_quiz_access_override_per_student'),
        ),
    ]
